// flutter_rust_bridge:generated-file-start
// This file is auto-generated by flutter_rust_bridge code generator.
// DO NOT EDIT THIS FILE MANUALLY.

import 'dart:async';
import 'dart:ffi';
import 'dart:isolate';
import 'package:flutter/foundation.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'bridge_definitions.dart';

/// Rust library for mesh_core
class RustLib extends BaseWire {
  RustLib({required super.pseudo}) : super();

  static late final RustLib _instance;
  static RustLib get instance => _instance;

  static Future<void> init({String? libPath}) async {
    _instance = await FullLib.create(libPath: libPath);
    debugPrint('RustLib initialized');
  }
}

// ============================================================================
// Function Handlers (Auto-generated stubs)
// These will be replaced when you run: flutter_rust_bridge_codegen
// ============================================================================

Future<Identity> generateIdentityHandler() async {
  return RustLib.instance.wasmBufferToStruct(
    await RustLib.instance.generateIdentity(),
    (dynamic raw) => Identity.fromMap(raw as Map<String, dynamic>),
  );
}

Future<bool> storeIdentityHandler({required Identity identity}) async {
  return await RustLib.instance.storeIdentity(identity: identity);
}

Future<Identity?> getCurrentIdentityHandler() async {
  return await RustLib.instance.getCurrentIdentity();
}

Future<EncryptedPayload> encryptMessageHandler({
  required String messageContent,
  required String recipientPublicKey,
}) async {
  return await RustLib.instance.encryptMessage(
    messageContent: messageContent,
    recipientPublicKey: recipientPublicKey,
  );
}

Future<String> decryptMessageHandler({
  required EncryptedPayload encryptedPayload,
  required String senderPublicKey,
}) async {
  return await RustLib.instance.decryptMessage(
    encryptedPayload: encryptedPayload,
    senderPublicKey: senderPublicKey,
  );
}

Future<Uint8List> createSyncDocumentHandler() async {
  return await RustLib.instance.createSyncDocument();
}

Future<Uint8List?> applySyncChangesHandler({
  required Uint8List document,
  required Uint8List changes,
}) async {
  return await RustLib.instance.applySyncChanges(
    document: document,
    changes: changes,
  );
}
